-- AlterTable
ALTER TABLE `Invite` MODIFY `role` ENUM('SYSTEM_ADMIN', 'PROPERTY_MANAGER', 'TENANT', 'VENDOR', 'ALL') NOT NULL;

-- AlterTable
ALTER TABLE `SidebarItem` MODIFY `role` ENUM('SYSTEM_ADMIN', 'PROPERTY_MANAGER', 'TENANT', 'VENDOR', 'ALL') NOT NULL;

-- AlterTable
ALTER TABLE `organization_users` MODIFY `role` ENUM('SYSTEM_ADMIN', 'PROPERTY_MANAGER', 'TENANT', 'VENDOR', 'ALL') NOT NULL;
